name: examen_ordinaria
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.1

environment:
  sdk: ^3.6.1

dependencies:
  google_fonts: ^6.2.1
  provider: ^6.1.5
  floor: ^1.5.0
  flutter:
    sdk: flutter
  html: ^0.15.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  floor_generator: ^1.5.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
